apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: demolabs
spec:
  storageClassName: manual_fake_sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
